"""
=============================================================================
BACKTESTING ENGINE — OVERALL SYSTEM GOAL
=============================================================================
This system takes historical 1-minute price data for a futures instrument,
runs a trading strategy against it, simulates realistic trade execution,
and produces a full performance report. The goal is to answer one question
honestly: does this strategy make money across different market conditions,
or does it only work sometimes?

The engine is organized into five layers that never import from each other
except through the master engine (backtest/engine.py):

    DATA LAYER        backtest/data/loader.py
    INDICATORS LAYER  backtest/indicators/volatility.py, regime.py
    STRATEGY LAYER    backtest/strategies/base.py, orb.py   <-- YOU ARE HERE
    EXECUTION LAYER   backtest/execution/fills.py
    METRICS LAYER     backtest/metrics/report.py

=============================================================================
THIS FILE — backtest/strategies/base.py
=============================================================================
Defines two things:

  1. Signal — a dataclass representing one potential trade entry. Every
     strategy returns a list of Signals. The execution layer consumes them.

  2. BaseStrategy — an Abstract Base Class (ABC) that every trading strategy
     must inherit from. It enforces a consistent interface so the engine can
     call any strategy the same way, without knowing anything about the
     strategy's internal logic.

HOW IT CONNECTS:
  - backtest/engine.py accepts any object whose class inherits BaseStrategy.
    The engine calls generate_signals() and validate_params() without caring
    which strategy it is.
  - backtest/strategies/orb.py (and any future strategy) must inherit from
    BaseStrategy and implement every @abstractmethod, or Python will refuse
    to instantiate it.
  - The Signal objects returned by generate_signals() are passed directly to
    backtest/execution/fills.py, which simulates the actual trade fills.
=============================================================================
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

import pandas as pd


# ---------------------------------------------------------------------------
# Signal dataclass
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """
    Represents a single trade opportunity generated by a strategy.

    A Signal is produced on bar N. The execution layer will attempt to enter
    the trade at the OPEN of bar N+1 (never on the close of bar N — see
    fills.py for the explanation of lookahead bias).

    Fields
    ------
    bar_index : int
        The integer positional index (iloc) in the main DataFrame where the
        signal fired. The execution layer uses bar_index + 1 as the entry bar.

    direction : str
        Either "long" (bet on price rising) or "short" (bet on price falling).

    stop_price : float
        The price at which the trade is considered wrong and must be closed.
        This is set by the strategy based on its logic (e.g., below the ORB
        low for a long trade). The execution layer does NOT move this.

    target_price : float
        The price at which the trade is taken off as a winner.

    metadata : dict[str, Any]
        A free-form dictionary for strategy-specific data that should be
        recorded in the trade log but is not part of universal trade logic.
        Example: ORB strategy stores orb_high and orb_low here.
        Non-ORB strategies leave this empty; the report layer fills those
        columns with None.

    WARNING: bar_index must be a positional integer index (df.iloc[bar_index]),
    NOT a timestamp label (df.loc[...]). Using a timestamp here would break
    silently on any day with missing bars (e.g., early close days, holidays).
    Always use iloc-based indexing downstream.
    """

    bar_index: int
    direction: str           # "long" or "short"
    stop_price: float
    target_price: float
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate the signal immediately on construction."""
        if self.direction not in ("long", "short"):
            raise ValueError(
                f"Signal.direction must be 'long' or 'short', got '{self.direction}'."
            )
        if self.bar_index < 0:
            raise ValueError(
                f"Signal.bar_index must be non-negative, got {self.bar_index}."
            )
        if self.stop_price <= 0 or self.target_price <= 0:
            raise ValueError(
                "Signal.stop_price and target_price must be positive price levels."
            )


# ---------------------------------------------------------------------------
# BaseStrategy abstract base class
# ---------------------------------------------------------------------------

class BaseStrategy(ABC):
    """
    Abstract base class that defines the interface every trading strategy must
    implement.

    Design rationale
    ----------------
    The engine (backtest/engine.py) needs to call generate_signals() on
    whatever strategy it receives. By requiring all strategies to inherit from
    BaseStrategy:

      1. GUARANTEED INTERFACE — Python raises TypeError at instantiation time
         if a required method is missing. Bugs surface early, not deep inside
         a backtest run.

      2. SWAPPABILITY — The engine never changes. Only the strategy object
         passed to it changes. This makes A/B testing strategies trivial.

      3. SHARED BOOKKEEPING — Common behavior (parameter merging, validation
         boilerplate) lives here once, rather than being copied into every
         strategy.

    How to write a new strategy
    ---------------------------
    1. Create a file in backtest/strategies/
    2. Import and inherit from BaseStrategy
    3. Define DEFAULT_PARAMS at the class level
    4. Implement name (property) and generate_signals()
    5. Optionally override validate_params() for parameter sanity checks

    Example skeleton::

        class MyStrategy(BaseStrategy):
            DEFAULT_PARAMS = {"lookback": 20, "rr": 2.0}

            @property
            def name(self) -> str:
                return "MyStrategy"

            def generate_signals(self, data, daily_indicators):
                signals = []
                # ... your logic here ...
                return signals
    """

    # Subclasses must define this at the class level.
    # It holds the default values for every parameter the strategy uses.
    # The __init__ below merges user-supplied params on top of these defaults.
    #
    # WARNING: Do NOT define DEFAULT_PARAMS as an instance variable inside
    # __init__. It must be a class-level attribute so that it exists before
    # __init__ runs (Python evaluates class bodies before __init__).
    DEFAULT_PARAMS: dict[str, Any] = {}

    def __init__(self, params: dict[str, Any] | None = None) -> None:
        """
        Initialise the strategy and merge user params with defaults.

        Parameters
        ----------
        params : dict or None
            Key/value overrides for any subset of DEFAULT_PARAMS. Values not
            supplied here are taken from DEFAULT_PARAMS. Unknown keys (keys
            that do not appear in DEFAULT_PARAMS) are accepted and stored, but
            validate_params() may choose to reject them.

            Passing None is equivalent to passing an empty dict — all defaults
            are used.

        Example
        -------
        >>> strat = ORBStrategy(params={"orb_minutes": 15, "rr": 2.0})
        # orb_minutes and rr are overridden; every other key keeps its default
        """
        # dict unpacking merges two dicts. The right side wins on collisions.
        # So user-supplied params override defaults, but defaults fill in gaps.
        self.params: dict[str, Any] = {**self.DEFAULT_PARAMS, **(params or {})}

        # Run subclass-specific validation immediately.
        # If params are invalid, we want to know before the backtest starts,
        # not three hours into a run.
        self.validate_params()

    # ------------------------------------------------------------------
    # Abstract methods — every subclass MUST implement these
    # ------------------------------------------------------------------

    @property
    @abstractmethod
    def name(self) -> str:
        """
        Human-readable strategy name used in report headers and file names.

        Must be a @property (not a plain attribute) so that it can be
        accessed on both the class and the instance without ambiguity.

        Example return values: "ORB_30min", "VWAP_Reversion", "Momentum_5m"
        """
        ...

    @abstractmethod
    def generate_signals(
        self,
        data: pd.DataFrame,
        daily_indicators: pd.DataFrame,
    ) -> list[Signal]:
        """
        Scan historical price data and return every trade signal the strategy
        would have generated.

        This is the core method. All strategy logic lives here.

        Parameters
        ----------
        data : pd.DataFrame
            The full 1-minute OHLCV DataFrame produced by data/loader.py.
            Index is a DatetimeIndex. Columns: open, high, low, close, volume.
            The data has already been cleaned and validated.

        daily_indicators : pd.DataFrame
            One row per trading day. Columns produced by indicators/regime.py:
                date         — the trading date (datetime.date)
                atr          — daily ATR value
                atr_above_avg — bool, True = high-vol regime
                adx          — daily ADX value
                regime       — one of the four regime label strings

        Returns
        -------
        list[Signal]
            A list of Signal objects in chronological order. May be empty if
            no signals were generated. The list must NEVER contain signals for
            the same bar_index twice (duplicate entries for the same bar).

        WARNING — LOOKAHEAD BIAS: This method may examine any data up to and
        including bar N. It must NEVER look at bar N+1 or later when deciding
        whether to generate a signal on bar N. Doing so would mean the
        strategy is "seeing the future," producing results that cannot be
        replicated in live trading. The execution layer enforces entry on
        bar N+1, but it cannot check whether the strategy itself peeked ahead.
        This is the responsibility of the strategy author.

        WARNING — DAILY INDICATOR ALIGNMENT: When reading daily_indicators for
        bar N, use the DATE of bar N to look up that day's indicators — not
        the index position. Dates ensure correct alignment across weekends,
        holidays, and any gaps in the minute data.
        """
        ...

    # ------------------------------------------------------------------
    # Optional override — subclasses may override this
    # ------------------------------------------------------------------

    def validate_params(self) -> None:
        """
        Check that self.params contains valid values and raise ValueError if not.

        The base implementation does nothing. Subclasses should override this
        to enforce their own parameter constraints.

        Called automatically at the end of __init__, so errors surface before
        any backtest runs.

        Example override in ORBStrategy::

            def validate_params(self) -> None:
                if not (1 <= self.params["orb_minutes"] <= 120):
                    raise ValueError("orb_minutes must be between 1 and 120.")
                if self.params["rr"] <= 0:
                    raise ValueError("rr (reward:risk) must be positive.")
        """
        pass

    # ------------------------------------------------------------------
    # Concrete helpers — available to all subclasses, no override needed
    # ------------------------------------------------------------------

    def __repr__(self) -> str:
        """
        Readable string representation of the strategy and its active params.

        Python calls __repr__ when you print a strategy object or inspect it
        in a debugger. Example output:
            ORBStrategy(params={'orb_minutes': 30, 'rr': 1.5, ...})
        """
        return f"{self.__class__.__name__}(params={self.params!r})"
